import * as React from 'react';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';

export default function ComboBox({ setSelectedCity }) {

    const handleSelectedCity = (e, value) => {
        setSelectedCity(value);
    }


    return (
        <Autocomplete
            disablePortal
            id="weather-combobox"
            options={cityList}
            sx={{ width: 300 }}
            renderInput={(params) => <TextField {...params} label="City" />}
            onChange={handleSelectedCity}
        />
    );
}


const cityList = [
    // Norte América
    { label: 'Mexico City', countryCode: 'MX' },
    { label: 'New York', countryCode: 'US' },
    { label: 'Los Angeles', countryCode: 'US' },
    { label: 'Toronto', countryCode: 'CA' },
    { label: 'Vancouver', countryCode: 'CA' },
    { label: 'Chicago', countryCode: 'US' },
    { label: 'Houston', countryCode: 'US' },
    { label: 'Montreal', countryCode: 'CA' },
    { label: 'Miami', countryCode: 'US' },
    { label: 'Atlanta', countryCode: 'US' },
    { label: 'Seattle', countryCode: 'US' },
    { label: 'San Francisco', countryCode: 'US' },
    { label: 'Dallas', countryCode: 'US' },
    { label: 'Denver', countryCode: 'US' },
    { label: 'Phoenix', countryCode: 'US' },
    { label: 'Boston', countryCode: 'US' },
    { label: 'Philadelphia', countryCode: 'US' },
    { label: 'Washington, D.C.', countryCode: 'US' },
    { label: 'San Diego', countryCode: 'US' },
    { label: 'Las Vegas', countryCode: 'US' },
    { label: 'Calgary', countryCode: 'CA' },
    { label: 'Edmonton', countryCode: 'CA' },
    { label: 'Ottawa', countryCode: 'CA' },
    { label: 'Quebec City', countryCode: 'CA' },
    { label: 'Winnipeg', countryCode: 'CA' },
    { label: 'Kingston', countryCode: 'JM' },
    { label: 'Havana', countryCode: 'CU' },
    { label: 'Santo Domingo', countryCode: 'DO' },
    { label: 'Guatemala City', countryCode: 'GT' },
    { label: 'San Salvador', countryCode: 'SV' },
    { label: 'Tegucigalpa', countryCode: 'HN' },
    { label: 'Managua', countryCode: 'NI' },
    { label: 'San Jose', countryCode: 'CR' },
    { label: 'Panama City', countryCode: 'PA' },
    { label: 'Belmopan', countryCode: 'BZ' },
    { label: 'San Pedro Sula', countryCode: 'HN' },
    { label: 'La Ceiba', countryCode: 'HN' },
    { label: 'San Miguel', countryCode: 'SV' },
    { label: 'Santa Ana', countryCode: 'SV' },
    // Sur América
    { label: 'Buenos Aires', countryCode: 'AR' },
    { label: 'Lima', countryCode: 'PE' },
    { label: 'Bogota', countryCode: 'CO' },
    { label: 'Santiago', countryCode: 'CL' },
    { label: 'Caracas', countryCode: 'VE' },
    { label: 'Georgetown', countryCode: 'GY' },
    { label: 'Brasilia', countryCode: 'BR' },
    { label: 'Fortaleza', countryCode: 'BR' },
    { label: 'Recife', countryCode: 'BR' },
    { label: 'Belem', countryCode: 'BR' },
    { label: 'Cuiaba', countryCode: 'BR' },
    { label: 'Goiania', countryCode: 'BR' },
    { label: 'Natal', countryCode: 'BR' },
    { label: 'Medellin', countryCode: 'CO' },
    { label: 'Cali', countryCode: 'CO' },
    { label: 'Barranquilla', countryCode: 'CO' },
    { label: 'Cartagena', countryCode: 'CO' },
    { label: 'Maracaibo', countryCode: 'VE' },
    { label: 'Valencia', countryCode: 'VE' },
    { label: 'Barquisimeto', countryCode: 'VE' },
    { label: 'Maracay', countryCode: 'VE' },
    { label: 'Guayaquil', countryCode: 'EC' },
    { label: 'Cuenca', countryCode: 'EC' },
    { label: 'Iquitos', countryCode: 'PE' },
    { label: 'Trujillo', countryCode: 'PE' },
    { label: 'Arequipa', countryCode: 'PE' },
    { label: 'La Serena', countryCode: 'CL' },
    { label: 'Antofagasta', countryCode: 'CL' },
    { label: 'Concepcion', countryCode: 'CL' },
    { label: 'Valdivia', countryCode: 'CL' },
    { label: 'Puerto Montt', countryCode: 'CL' },
    { label: 'Punta Arenas', countryCode: 'CL' },
    { label: 'Cochabamba', countryCode: 'BO' },
    { label: 'Sucre', countryCode: 'BO' },
    { label: 'Santa Cruz', countryCode: 'BO' },
    { label: 'Oruro', countryCode: 'BO' },
    { label: 'Potosi', countryCode: 'BO' },
    { label: 'La Paz', countryCode: 'BO' },
    { label: 'Paramaribo', countryCode: 'SR' },
    { label: 'Cayenne', countryCode: 'GF' },
    { label: 'Boa Vista', countryCode: 'BR' },
    { label: 'Manaus', countryCode: 'BR' },
    { label: 'Macapa', countryCode: 'BR' },
    { label: 'Santarem', countryCode: 'BR' },
    { label: 'Porto Velho', countryCode: 'BR' },
    { label: 'Rio Branco', countryCode: 'BR' },
    { label: 'Campo Grande', countryCode: 'BR' },
    { label: 'Vitoria', countryCode: 'BR' },
    { label: 'Belo Horizonte', countryCode: 'BR' },
    { label: 'Sao Paulo', countryCode: 'BR' },
    { label: 'Rio de Janeiro', countryCode: 'BR' },
    { label: 'Curitiba', countryCode: 'BR' },
    { label: 'Porto Alegre', countryCode: 'BR' },
    { label: 'Montevideo', countryCode: 'UY' },
    { label: 'Colonia del Sacramento', countryCode: 'UY' },
    { label: 'Punta del Este', countryCode: 'UY' },
    { label: 'Asuncion', countryCode: 'PY' },
    { label: 'Ciudad del Este', countryCode: 'PY' },
    { label: 'Encarnacion', countryCode: 'PY' },
    // Europa
    { label: 'London', countryCode: 'GB' },
    { label: 'Paris', countryCode: 'FR' },
    { label: 'Rome', countryCode: 'IT' },
    { label: 'Madrid', countryCode: 'ES' },
    { label: 'Berlin', countryCode: 'DE' },
    { label: 'Athens', countryCode: 'GR' },
    { label: 'Lisbon', countryCode: 'PT' },
    { label: 'Vienna', countryCode: 'AT' },
    { label: 'Budapest', countryCode: 'HU' },
    { label: 'Dublin', countryCode: 'IE' },
    { label: 'Stockholm', countryCode: 'SE' },
    { label: 'Oslo', countryCode: 'NO' },
    { label: 'Copenhagen', countryCode: 'DK' },
    { label: 'Helsinki', countryCode: 'FI' },
    { label: 'Warsaw', countryCode: 'PL' },
    { label: 'Moscow', countryCode: 'RU' },
    { label: 'Zurich', countryCode: 'CH' },
    { label: 'Geneva', countryCode: 'CH' },
    { label: 'Brussels', countryCode: 'BE' },
    { label: 'Barcelona', countryCode: 'ES' },
    { label: 'Milan', countryCode: 'IT' },
    { label: 'Munich', countryCode: 'DE' },
    { label: 'Amsterdam', countryCode: 'NL' },
    { label: 'The Hague', countryCode: 'NL' },
    { label: 'Dubrovnik', countryCode: 'HR' },
    { label: 'Prague', countryCode: 'CZ' },
    { label: 'Bucharest', countryCode: 'RO' },
    { label: 'Sofia', countryCode: 'BG' },
    { label: 'Edinburgh', countryCode: 'GB' },
    { label: 'Manchester', countryCode: 'GB' },
    { label: 'Birmingham', countryCode: 'GB' },
    { label: 'Glasgow', countryCode: 'GB' },
    { label: 'Liverpool', countryCode: 'GB' },
    { label: 'Cardiff', countryCode: 'GB' },
    { label: 'Belfast', countryCode: 'GB' },
    // Asia
    { label: 'Tokyo', countryCode: 'JP' },
    { label: 'Osaka', countryCode: 'JP' },
    { label: 'Beijing', countryCode: 'CN' },
    { label: 'Shanghai', countryCode: 'CN' },
    { label: 'Seoul', countryCode: 'KR' },
    { label: 'Bangkok', countryCode: 'TH' },
    { label: 'Singapore', countryCode: 'SG' },
    { label: 'Kuala Lumpur', countryCode: 'MY' },
    { label: 'Jakarta', countryCode: 'ID' },
    { label: 'Manila', countryCode: 'PH' },
    { label: 'Hanoi', countryCode: 'VN' },
    { label: 'Ho Chi Minh City', countryCode: 'VN' },
    { label: 'Mumbai', countryCode: 'IN' },
    { label: 'New Delhi', countryCode: 'IN' },
    { label: 'Kolkata', countryCode: 'IN' },
    { label: 'Bangalore', countryCode: 'IN' },
    { label: 'Chennai', countryCode: 'IN' },
    { label: 'Dubai', countryCode: 'AE' },
    { label: 'Abu Dhabi', countryCode: 'AE' },
    { label: 'Doha', countryCode: 'QA' },
    { label: 'Riyadh', countryCode: 'SA' },
    { label: 'Jeddah', countryCode: 'SA' },
    { label: 'Amman', countryCode: 'JO' },
    { label: 'Jerusalem', countryCode: 'IL' },
    { label: 'Tel Aviv', countryCode: 'IL' },
    { label: 'Kuwait City', countryCode: 'KW' },
    { label: 'Muscat', countryCode: 'OM' },
    { label: 'Tehran', countryCode: 'IR' },
    { label: 'Baghdad', countryCode: 'IQ' },
    { label: 'Istanbul', countryCode: 'TR' },
    { label: 'Ankara', countryCode: 'TR' },
    { label: 'Baku', countryCode: 'AZ' },
    { label: 'Tbilisi', countryCode: 'GE' },
    { label: 'Yerevan', countryCode: 'AM' },
    // África
    { label: 'Cairo', countryCode: 'EG' },
    { label: 'Alexandria', countryCode: 'EG' },
    { label: 'Cape Town', countryCode: 'ZA' },
    { label: 'Johannesburg', countryCode: 'ZA' },
    { label: 'Nairobi', countryCode: 'KE' },
    { label: 'Casablanca', countryCode: 'MA' },
    { label: 'Marrakech', countryCode: 'MA' },
    { label: 'Lagos', countryCode: 'NG' },
    { label: 'Accra', countryCode: 'GH' },
    { label: 'Dakar', countryCode: 'SN' },
    { label: 'Tunis', countryCode: 'TN' },
    { label: 'Algiers', countryCode: 'DZ' },
    { label: 'Luanda', countryCode: 'AO' },
    { label: 'Dar es Salaam', countryCode: 'TZ' },
    { label: 'Addis Ababa', countryCode: 'ET' },
    { label: 'N\'Djamena', countryCode: 'TD' },
    // Oceanía
    { label: 'Sydney', countryCode: 'AU' },
    { label: 'Melbourne', countryCode: 'AU' },
    { label: 'Brisbane', countryCode: 'AU' },
    { label: 'Perth', countryCode: 'AU' },
    { label: 'Auckland', countryCode: 'NZ' },
    { label: 'Wellington', countryCode: 'NZ' },
    { label: 'Christchurch', countryCode: 'NZ' },
    { label: 'Nouméa', countryCode: 'NC' },



];
